services:
  django:
      build: .
      command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./mysite:/app
      environment:
        DATABASE_HOST: mysql-mysql-1 # 指定 MySQL 容器的服务名
        DATABASE_PORT: 3306
        DATABASE_NAME: docker-mysql-quickstart
        DATABASE_USER: qzj
        DATABASE_PASSWORD: db123456
      ports:
        - "8000:8000"
      networks:
        - mynetwork

networks:
  mynetwork:
    external: true