# mysql.compose file

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: db123456
        MYSQL_DATABASE: docker-mysql-quickstart
        MYSQL_USER: qzj
        MYSQL_PASSWORD: db123456
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql  # 持久化卷
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
networks:
  mynetwork:
    driver: bridge
      
volumes:
  mysql_data:
    driver: local  # 使用本地卷驱动